# this need to be apply first before installing certificate for any url
# =====================================================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@digitalwitchng.online
    privateKeySecretRef:
      name: letsencrypt-prod-cluster-issuer
    solvers:
    - http01:
        ingress:
          ingressClassName: external-nginx
